export const CHANGE_ALBUM_ID = "CHANGE_ALBUM_ID";

export const CHANGE_ACTIVE_USER = "CHANGE_ACTIVE_USER";

export const CHANGE_ALBUMS = "CHANGE_ALBUMS";

export const CHANGE_INITIAL_STATE_MULTI_ALBUM = "CHANGE_INITIAL_STATE_MULTI_ALBUM";

export const CHANGE_AUTHOR = "CHANGE_AUTHOR";

export const RETURN_IN_INITIAL_STATE_COMMENTS_PAGE = "RETURN_IN_INITIAL_STATE_COMMENTS_PAGE";

export const INFO_ABOUT_USER_CHANGE_CITY_USER = "INFO_ABOUT_USER_CHANGE_CITY_USER";

export const CHANGE_COMMENT = "CHANGE_COMMENT";

export const CHANGE_DATA = "CHANGE_DATA";

export const RETURN_IN_INITIAL_STATE_COMMENTS_PAGE_DATA = "RETURN_IN_INITIAL_STATE_COMMENTS_PAGE_DATA";

export const CHANGE_DELETE_ITEM = "CHANGE_DELETE_ITEM";

export const CHANGE_EMAIL = "CHANGE_EMAIL";

export const INFO_ABOUT_USER_CHANGE_EMAIL_USER = "INFO_ABOUT_USER_CHANGE_EMAIL_USER";

export const CHANGE_VISIBLE = "CHANGE_VISIBLE";

export const CHANGE_FLAG_PROFILE = "CHANGE_FLAG_PROFILE";

export const VISIBLE_POST_POST_ID = "VISIBLE_POST_POST_ID";

export const CHANGE_IMAGES = "CHANGE_IMAGES";

export const DELETE_PHOTO_FROM_IMAGES = "DELETE_PHOTO_FROM_IMAGES";

export const CHANGE_USER_REGISTRATION = "CHANGE_USER_REGISTRATION";

export const CHANGE_VISIBLE_ALBUM = "CHANGE_VISIBLE_ALBUM";

export const CHANGE_VISIBLE_AUTHORIZATION = "CHANGE_VISIBLE_AUTHORIZATION";

export const CHANGE_VISIBLE_BIGGER_PHOTO = "CHANGE_VISIBLE_BIGGER_PHOTO";

export const CHANGE_VISIBLE_INFORMATION_FROM_PROFILE = "CHANGE_VISIBLE_INFORMATION_FROM_PROFILE";

export const CHANGE_VISIBLE_CHECK_MULTI_ALBUM_FROM_PROFILE = "CHANGE_VISIBLE_CHECK_MULTI_ALBUM_FROM_PROFILE";

export const VISIBLE_POST = "VISIBLE_POST";

export const VISIBLE_POST_PART = "VISIBLE_POST_PART";

export const CHANGE_VISIBLE_PROFILE = "CHANGE_VISIBLE_PROFILE";

export const CHANGE_VISIBLE_REGISTRATIONS = "CHANGE_VISIBLE_REGISTRATIONS";

export const INFO_ABOUT_USER_CHANGE_NAME = "INFO_ABOUT_USER_CHANGE_NAME";

export const CHANGE_INITIAL_STATE_IMG_NAME = "CHANGE_INITIAL_STATE_IMG_NAME";

export const CHANGE_NEW_ALBUM_NAME = "CHANGE_NEW_ALBUM_NAME";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

export const CHANGE_INITIAL_STATE_IMG_PATH = "CHANGE_INITIAL_STATE_IMG_PATH";

export const CHANGE_PATH = "CHANGE_PATH";

export const CHANGE_POSTS = "CHANGE_POSTS";

export const CHANGE_IN_INITIAL_STATE_IMAGES = "CHANGE_IN_INITIAL_STATE_IMAGES";

export const CHANGE__PSEOUDONYM_REGISTRATION = "CHANGE__PSEOUDONYM_REGISTRATION";

export const CHANGE__EMAIL_REGISTRATION = "CHANGE__EMAIL_REGISTRATION";

export const CHANGE__PASSWORD_REGISTRATION = "CHANGE__PASSWORD_REGISTRATION";

export const INFO_ABOUT_USER_CHANGE_SPHERE_USER = "INFO_ABOUT_USER_CHANGE_SPHERE_USER";

export const CHANGE_BIGGER_PHOTO_PATH = "CHANGE_BIGGER_PHOTO_PATH";

export const CHANGE_SUBPOSTS = "CHANGE_SUBPOSTS";

export const CHANGE_IN_INITIAL_STATE_SUB_POSTS = "CHANGE_IN_INITIAL_STATE_SUB_POSTS";

export const INFO_ABOUT_USER_CHANGE_SURNAME = "INFO_ABOUT_USER_CHANGE_SURNAME";

export const CHANGE_NAME_IMAGE = "CHANGE_NAME_IMAGE";

export const isAuthenticated = {
    isAuthenticated : false,
    authenticate() {
        this.isAuthenticated = true;
    },
}



