let defaultState={
    email: "",
    password: "",
    activeUserId: "",
    isVisibleProfile: false,
    isVisibleInformation: false,
    isVisibleAuthorization: false,
    name: "",
    surname: "",
    emailUser: "",
    sphere: "",
    city: "",
    pseoudonym: "",
    images: [],
    deleteItem: "Enter the name of image...",
    nameImg: "Enter the name of image...",
    path: "Enter the path of image...",
    idPost: "",
    isVisiblePost: false,
    isVisiblePosts: true,
    subPosts: [],
    idUser: 0,
    isVisibleAlbum: false,
    posts: [],
    author: [],
    data: [],
    comment: "",
    flagForCheckPageCommentsOrProfile: false,
    RETURN_IN_INITIAL_STATE_IMAGE: false,
    isVisibleRegistration: false,
    registrationEmail: "",
    registrationPassword: "",
    isRegistrationUser: false,
    srcPhotoBigger:"",
    isVisibleBiggerPhoto: false
};

export default defaultState;